version: "3.1"

services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres-food-delivery
    environment:
      POSTGRES_USER: foodDelivery
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: foodDelivery
    expose:
      - "5434"
    ports:
      - "5434:5434"

    command: -p 5434
